# Base image with Node.js and browsers
FROM cypress/browsers:node-20.15.1-chrome-123.0.0-1

# Set working directory
WORKDIR /usr/src/app

# Install Cypress
RUN npm install cypress@13.13.1

# Copy Cypress configuration and tests
COPY cypress /usr/src/app/cypress
COPY cypress.config.js /usr/src/app/cypress.config.js

# Confirm the Cypress installation
RUN npx cypress verify

# Start the Cypress tests directly
ENTRYPOINT ["npx", "cypress", "run", "--config-file", "cypress.config.js"]
