name: CI

on:
  push:
    branches:
      - master
      - angular-cypress
  pull_request:
    branches:
      - master
      - angular-cypress

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Alignez la version avec celle utilisée dans votre Dockerfile

    - name: Install Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo curl -L "https://github.com/docker/compose/releases/download/2.17.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and start services
      run: |
        docker-compose up -d --build

    - name: Run Cypress tests
      run: |
        docker-compose run cypress ./node_modules/.bin/cypress run --config baseUrl=http://127.0.0.1

    - name: Stop and remove services
      run: |
        docker-compose down
