name: CI

on:
  push:
    branches:
      - master
      - angular-cypress
  pull_request:
    branches:
      - master
      - angular-cypress

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Updated Node.js version

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get remove -y containerd containerd.io
        sudo apt-get autoremove -y
        sudo apt-get install -y docker.io

    - name: Install Docker Compose
      run: |
        DOCKER_COMPOSE_VERSION=1.29.2
        sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and start services
      run: |
        docker-compose up -d --build

    - name: Run Cypress tests
      run: |
        docker-compose run cypress npx cypress run --config-file=cypress.config.js

    - name: Stop and remove services
      run: |
        docker-compose down
