name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
          
          # Add Docker's official GPG key
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc
          
          # Set up the Docker repository
          echo "deb [arch=$(dpkg --print-architecture) ] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          # Install Docker
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

          # Check Docker version
          sudo docker --version

      - name: Build Docker Image
        run: |
          sudo docker build -t my-angular-app:latest .

      - name: Run Docker Container
        run: |
          sudo docker run -d -p 8080:80 my-angular-app:latest

      - name: Verify Docker Container
        run: |
          curl -f http://localhost:8080 || exit 1

      - name: Run Cypress Tests
        run: |
          # Assurez-vous que Cypress est installé et configuré correctement
          npx cypress run
